### ISSUE TITLE
Font display in tables

### ISSUE THREAD

**Issue by StarWanan** [Bluemoondragon07/obsidian-light-and-bright-theme#1]
Thank you for the delightful theme! I stumbled upon it and love this theme very much. But I found that when editing the table, the font blends in with the background (in light color mode), like these:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/61813270/218772287-0a006eb1-9a8f-448d-9760-c881acc75ea0.png">

<img width="257" alt="image" src="https://user-images.githubusercontent.com/61813270/218772353-15ae861a-8105-4260-aaff-5b26de9ca519.png">

And I'm very much looking forward to the other color themes you show up, good luck!

**Comment by Bluemoondragon07** [comment]
Thanks, StarWanan. I'm glad you like the theme! I'll be sure to fix this in the style settings update coming up.

**Comment by Bluemoondragon07** [comment]
This issue has been fixed in the latest update!
