### ISSUE TITLE
May I ask how to adjust the width of content?

### ISSUE THREAD

**Issue by gxhoho** [Bluemoondragon07/obsidian-light-and-bright-theme#2]
Hi, thanks for this awesome theme, I love it so much!!
I just feel currently the width is a bit small and want to adjust it to around 1000px, but didn't figured out the logic of .css file.
So do you mind give me a hint? Thanks!

**Comment by Bluemoondragon07** [comment]
You can adjust it with this snippet:
```css
body {
--file-line-width: 1000px;
}
```
Glad you like the theme :)
