### ISSUE TITLE
Partially displayed mermaid view

### ISSUE THREAD

**Issue by xsinbh** [Bluemoondragon07/obsidian-light-and-bright-theme#5]
## Problem
code:
```
graph BT
a --> duwqihwq --> djwiqjdqidioqfjwofefrnrnurwu --> uqwiufhwiufewuiw
b --> jdiwoqdwiqdjwfiefq --> dwiqfwiffwiefwjf --> dioqwifjqwofijowfrngr --> diqjowdidjwoifjefjgjrgjgjriuaohuhweiufheufhwif --> e
e --> ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp
f --> a & wisjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
```
The effect:
![image](https://github.com/Bluemoondragon07/obsidian-light-and-bright-theme/assets/112634985/4d2fffda-74c6-4e41-a0fc-3b0d0cb1297b)

The graph was partially showed. And there was no rolling bar.

## Anticipation
3 solution I've found and my personal evaluation:
![image](https://github.com/Bluemoondragon07/obsidian-light-and-bright-theme/assets/112634985/46812bc9-c79a-4b74-9a41-1f6818ad552b)

Best: Add a left rolling bar, just as Github does.
![image](https://github.com/Bluemoondragon07/obsidian-light-and-bright-theme/assets/112634985/44b8be20-d6fa-4ae1-ac5e-e458b1b1df0b)

90% best: Zoom out to fit the view at the cost of reducing font size
![image](https://github.com/Bluemoondragon07/obsidian-light-and-bright-theme/assets/112634985/1985d16a-ace1-489b-9e7e-fb8e208a8384)

Good: Add a bottom rolling bar

**Comment by xsinbh** [comment]
When the graph is too large in size, even in full screen can't I be able to see the whole content.

**Comment by Bluemoondragon07** [comment]
Thank you for pointing out this issue. Would you be willing to paste the mermaid code here so that I could test it out?

**Comment by Bluemoondragon07** [comment]
From my experimenting with your mermaid code, the theme displays it just as the default theme does. I do not think it high priority to change the styling in edit mode, since the full graph can be seen in reading mode. I will definitely keep this in mind when I have time to make another update, though.
